// <auto-generated />
using System;
using BelezaFut.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BelezaFut.Migrations
{
    [DbContext(typeof(BelezaFutContext))]
    [Migration("20210611190608_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("BelezaFut.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Posicao")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("timeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("timeId");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("BelezaFut.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abrev")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnico")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("BelezaFut.Models.Jogador", b =>
                {
                    b.HasOne("BelezaFut.Models.Time", "time")
                        .WithMany()
                        .HasForeignKey("timeId");

                    b.Navigation("time");
                });
#pragma warning restore 612, 618
        }
    }
}
